# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 羽天珼岸 . HakureiWing - Powerd by 0MuMDAU
email: m85091081@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://news.hakurei.com.tw" # the base hostname & protocol for your site
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"
# Build settings
markdown: kramdown
